name: Cypress Tests

on: push

jobs:
  cypress-run:
    env:
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
      NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check env vars
        run: echo "env var 1=$NEXT_PUBLIC_SUPABASE_URL"
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start